# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mary Knize
email: maryknize@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a front-end web developer and indie game developer. JavaScript, HTML, CSS, PHP, C#, Unity 3D. I learn new things every day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "captainpainway.github.io" # the base hostname & protocol for your site
twitter_username: captainpainway
github_username:  captainpainway

# Build settings
markdown: kramdown
